algoritmo "restaurante"

var
 sucos, marmitex, conta, precosuco, precocomida: real
inicio
escreval ("Quantos sucos foram vendidos?")
leia(sucos)
escreval("Qual o preço do suco?")
leia (precosuco)
 escreval ("Quantas marmitex foram vendidas?")
 leia (marmitex)
 escreval ("Qual o peço das marmitex?")
 leia (precocomida)
 conta:= (sucos*precosuco)+(marmitex*precocomida)
 escreval("Ao final do dia o restaurante receberá em dinheiro...",conta)





fimalgoritmo
